version: "3.3"            # 表示使用docker-compose.yml的Version 2 file format编写
services:
  consumer-movie-feign-with-hystrix-stream:     # 默认情况下，其它服务可以使用服务名称links到该服务
    image: microservice-consumer-movie-feign-with-hystrix-stream:latest
    container_name: consumer-movie-feign-with-hystrix-stream
    hostname: movie-feign
    restart: always
    ports:
      - 8028:8028
    environment:
      - spring.profiles.active=consumer1
      - eureka.instance.ip-address=192.168.96.1
    volumes:
      - /host_mnt/d/export/:/export/
