version: "3.3"            # 表示使用docker-compose.yml的Version 2 file format编写
services:
  consumer-movie-ribbon-with-hystrix:     # 默认情况下，其它服务可以使用服务名称links到该服务
    image: microservice-consumer-movie-ribbon-with-hystrix:latest
    container_name: consumer-movie-ribbon-with-hystrix
    hostname: movie.ribbon
    restart: always
    ports:
      - 8015:8015
    environment:
      - spring.profiles.active=consumer1
      - eureka.instance.ip-address=192.168.96.1
    volumes:
      - /host_mnt/d/export/:/export/
