version: "3.3"            # 表示使用docker-compose.yml的Version 2 file format编写
services:
  hystrix-turbine:     # 默认情况下，其它服务可以使用服务名称links到该服务
    image: microservice-hystrix-turbine:latest
    container_name: hystrix-turbine
    hostname: hystrix
    restart: always
    ports:
      - 8031:8031
    environment:
      - eureka.instance.ip-address=192.168.96.1
    volumes:
      - /host_mnt/d/export/:/export/
